logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: TrpcHttpGateway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=gateway-env, TrpcHttpGateway
      routes:
        - id: "serviceA"
          uri: "http://127.0.0.1:8091"
          predicates:
            - Path=/cgi-bin/**
          filters:
            - RewritePath=/cgi-bin/ , /
            - PreserveHostHeader
        - id: "serviceB"
          uri: "trpc://testTrpcClient/trpc.test.demo.Hello/SayHello"
          predicates:
            - Path=/trpc/**
          filters:
            - name: Trpc
              args:
                metadata: "valueB"
        - id: "serviceC"
          uri: "trpc://testTrpcClient/trpc.test.demo.Hello/SayHello"
          predicates:
            - Path=/trpc1/**
          filters:
            - name: Trpc
              args:
                metadata: "valueC"
                responseRewriter: "com.tencent.trpc.spring.cloud.gateway.rewriter.DefaultTrpcRequestRewriter"

trpc:
  client:
    service:
      - name: testHttpClient
        interface: com.tencent.trpc.core.rpc.GenericClient
        naming_url: ip://127.0.0.1:8091
        protocol: http
        transporter: jetty
        serialization: json
      - name: testTrpcClient
        interface: com.tencent.trpc.core.rpc.GenericClient
        naming_url: ip://127.0.0.1:8090 # polaris://trpc.trpc.test.demo.Hello.TestPolarisTRPC
        protocol: trpc
        serialization: json